name: test workflow
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
env:
  AWS_REGION: us-east-2
permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    name: Deploy QS Cron Service - Dev
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Golang!"