name: test workflow
on:
  push:
    branches:
      - "master"
      - "main"
  workflow_dispatch:

env:
  Region: us-east-1
  ECR_REPOSITORY: abc-test
  Aws_account_id: 947082213778
  version: v1
  imagename:  facebook_img

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

defaults:
  run:
    working-directory: ./myfirstcodebase/

jobs:
  to_ecr_pusher:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello Saksham!"
        shell: bash
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::947082213778:role/testrole
          role-session-name: samplerolesession
          aws-region: us-east-1
      - name: Create ECR repo if missing
        run: |
          aws ecr describe-repositories --repository-names $ECR_REPOSITORY || aws ecr create-repository --repository-name $ECR_REPOSITORY
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: find IMAGE_TAG
        run: |
          IMAGE_TAG=${{ github.sha }}
          echo IMAGE_TAG: $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      - name: Set Permissions
        run: chmod +x ./Scripts/build-and-push-image-to-ecr.sh
      
      - name: Running the Script
        run: |
         ./Scripts/build-and-push-image-to-ecr.sh

  print_golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello Golang!"

