name: test workflow
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
    
defaults:
  run:
    working-directory: ./myfirstcodebase
permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    name: Deploy QS Cron Service - Dev
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Golang!"