name: test workflow
on:
  push:
    branches:
      - "master"
      - "main"
  workflow_dispatch:
  

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello Saksham!"
        shell: bash

  print_golang:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Golang!"
        shell: bash